version: '3.1'

services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=1234
    #   - MONGO_INITDB_DATABASE=queue
    volumes:
      # - ./init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./db:/data/db
